name = "leanur"
version = "0.0.1"
defaultTargets = ["Leanur", "leanur"]
testDriver = "LeanurTests"

[[lean_exe]]
name = "leanur"
root = "Main"
exeName = "leanur"
supportInterpreter = true

[[lean_lib]]
name = "Leanur"

# testing

[[lean_exe]]
name = "LeanurTests"
root = "Test.Fixtures"
exeName = "leanur_tests"
extraDepTargets = ["Fixtures"]
supportInterpreter = true


[[lean_lib]]
name = "Fixtures"
roots = [
  "Fixtures.Expr",
  "Fixtures.Basic",
  "Fixtures.Recursion",
  # "Fixtures.Jock.Dec",
]

# dependencies

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.17.0-rc1"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.17.0-rc1"
